name: CI

on:
  - pull_request
  - push
  - workflow_dispatch

jobs:
  node-ci:
    name: Node CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gabrielrufino/node-ci@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sonar-token: ${{ secrets.SONAR_TOKEN }}
  tests:
    name: Tests
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [16, 18, 20]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i -g npm@8
      - run: npm ci
      - run: npm run test:cov
      - uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
